title: 3D Printing Blog by James Armstrong
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9083242
  brandStrength: 0.375
  lightness: 0.5838886
  brandColors:
    - '#020202'
    - '#FFFFFF'
    - '#0F778F'
    - '#41A2CC'
    - '#8DE2F8'
  rhythmicContrast: 0.7636921
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 3D Printing Blog
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5948749
layout_spectrum: 0.8093448
