title: 3D Printing Blog by James Armstrong
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9083242
  brandStrength: 0.375
  rhythmicContrast: 0.7636921
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.5838886
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 3D Printing Blog
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5948749
layout_spectrum: 0.9888059
